"""Task 0.4 gate: the C-port per-substep reference dump is well-formed.

Validates that the fixture pi_cdump.00000 (generated by fesom_dump.c on the pi
mesh, PP + linfs + opt_visc7, npes=1) contains every node *and* element substep
record the JAX port will verify against. Skips cleanly if the fixture is absent.
"""

import numpy as np

# (substep_id, field_name) expected at step 1.
EXPECT_STEP1 = {
    (1, "density"), (1, "pressure"), (1, "bvfreq"),       # EOS / N²   (node)
    (3, "pgf_x"), (3, "pgf_y"),                            # PGF        (elem)
    (4, "Kv"), (4, "Av"),                                  # mixing     (node+elem)
    (5, "uv_rhs_u"), (5, "uv_rhs_v"),                      # vel_rhs    (elem)
    (6, "uv_rhs_u"), (6, "uv_rhs_v"),                      # visc filt  (elem)
    (7, "uv_rhs_u"), (7, "uv_rhs_v"),                      # impl visc  (elem)
    (8, "ssh_rhs"),                                        # ssh rhs    (node)
    (9, "d_eta"),                                          # ssh solve  (node)
    (10, "uv_u"), (10, "uv_v"),                            # update vel (elem)
    (11, "hbar"), (12, "eta_n"),                           # hbar/eta_n (node)
    (13, "hnode_new"), (13, "w"),                          # ALE        (node)
    (15, "T"), (15, "S"), (16, "hnode"),                   # tracers/thickness (node)
}

NODE_FIELDS = {"density", "pressure", "bvfreq", "Kv", "ssh_rhs", "d_eta", "hbar",
               "eta_n", "hnode_new", "w", "T", "S", "hnode"}
ELEM_FIELDS = {"pgf_x", "pgf_y", "Av", "uv_rhs_u", "uv_rhs_v", "uv_u", "uv_v"}
NODE_PROBES = {1001, 1500, 2000, 2500, 3000}
N_ELEM2D = 5839  # pi


def test_cdump_has_all_substep_records(load_dump):
    recs = load_dump("pi_cdump.00000")
    step1 = {(r.substep, r.field) for r in recs if r.step == 1}
    missing = EXPECT_STEP1 - step1
    assert not missing, f"missing step-1 records: {sorted(missing)}"


def test_cdump_probes_and_values(load_dump):
    recs = load_dump("pi_cdump.00000")
    for r in recs:
        assert r.nlevels >= 1, r
        assert np.all(np.isfinite(r.values)), f"non-finite in {r.field}@sub{r.substep}"
        if r.field in NODE_FIELDS:
            assert r.probe_gid in NODE_PROBES, f"node field {r.field} bad probe {r.probe_gid}"
        elif r.field in ELEM_FIELDS:
            assert 1 <= r.probe_gid <= N_ELEM2D, f"elem field {r.field} bad gid {r.probe_gid}"
    # node probe 1001 (the pinned default) must be present
    assert 1001 in {r.probe_gid for r in recs if r.field in NODE_FIELDS}


def test_cdump_captured_ten_steps(load_dump):
    recs = load_dump("pi_cdump.00000")
    assert max(r.step for r in recs) == 10
    # density column at probe 1001 has the right depth (nlevels_nod2D=31 there)
    d1 = [r for r in recs if r.step == 1 and r.substep == 1
          and r.field == "density" and r.probe_gid == 1001]
    assert len(d1) == 1 and d1[0].nlevels == 31
