"""CORE2 assembled step + surface forcing gate — Phase 5, Task 5.6 acceptance.

Runs the full assembled ocean step on the CORE2 mesh (PHC IC + JRA55 bulk + SSS/runoff
+ shortwave penetration + the static ice mask) and verifies it against the C per-substep
dump (``data/step_dump_core2/core2_cdump.00000``, generated by
``port2/jobs/jax_step_dump_core2.sh`` at the matched config: PP, no GM/Redi, ice
dyn/adv/thermo off, ``FESOM_BULK_FIXED_ITERS=1``, dt=500).

Three gates:

* **Surface forcing** (``compute_surface_fluxes`` from the PHC IC): ``heat_flux``
  (post-shortwave-penetration), ``water_flux``, ``virtual_salt``, ``relax_salt``,
  ``sw_3d`` — MAP/reduction class (~1e-13 .. 1e-20).
* **Integrated step 1** (one eager step): post-step ``T``/``S`` — **bit-exact-class**
  (~1e-14). This is the comprehensive gate: it depends on every upstream kernel (EOS,
  PGF, PP, momentum, CG SSH, ALE, FCT, vertical diffusion) AND the new surface BCs, so a
  tight match validates the whole assembled CORE2 step.
* **Evolution** (steps 2–3): post-step ``T``/``S`` stay scatter-class (~1e-9), validating
  the loop-carried forcing (jra date progression, AB2 history, the step≥2 ice-ocean drag).

SKIPS cleanly if the CORE2 mesh / PHC IC cache / dump fixture are absent.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from fesom_jax import core2_forcing, io_dump, ssh
from fesom_jax import step as stepmod
from fesom_jax.mesh import load_mesh
from fesom_jax.phc_ic import core2_initial_state
from fesom_jax.verify import compare_column

ROOT = Path(__file__).resolve().parents[2]
MESH_DIR = ROOT / "data" / "mesh_core2"
IC_DIR = ROOT / "data" / "ic_core2"
DUMP = ROOT / "data" / "step_dump_core2" / "core2_cdump.00000"
DT = 500.0
YEAR = 1958
NSTEPS = 3
PROBES = [1001, 33778, 43828, 61202, 66921, 79663, 94122]

pytestmark = pytest.mark.skipif(
    not (MESH_DIR.exists() and (IC_DIR / "T_ic.npy").exists() and DUMP.exists()),
    reason="CORE2 mesh / PHC IC / step dump missing (run Task 5.1/5.2 + "
           "port2/jobs/jax_step_dump_core2.sh)",
)


@pytest.fixture(scope="module")
def run3():
    """Build the CORE2 model + forcing and run ``NSTEPS`` eager steps, caching each
    step's surface fluxes + post-step state (eager ~32 s/step — run once for the
    module)."""
    mesh = load_mesh(MESH_DIR)
    state = core2_initial_state(mesh, IC_DIR)
    op = ssh.build_ssh_operator(mesh, dt=DT)
    cf = core2_forcing.build_core_forcing(mesh, YEAR, sst_ic=np.asarray(state.T[:, 0]))
    fs = cf.static
    dates = core2_forcing.dates_for_steps(YEAR, DT, NSTEPS)
    recs = io_dump.load_records(DUMP)

    steps = []                              # (sfx_n, state_after_n) for n=1..NSTEPS
    st = state
    for n in range(NSTEPS):
        sf = cf.step_forcing(*dates[n])
        sfx = core2_forcing.compute_surface_fluxes(mesh, st, sf, fs, dt=DT)
        st = stepmod.step(st, mesh, op, None, dt=DT, is_first_step=(n == 0),
                          step_forcing=sf, forcing_static=fs)
        steps.append((sfx, st))
    return dict(mesh=mesh, fs=fs, recs=recs, steps=steps)


def _maxabs(jax_arr, recs, step, sub, field, kind):
    """Max |Δ| over the probe columns for one (step, substep, field)."""
    a = np.asarray(jax_arr)
    worst = 0.0
    for g in PROBES:
        r = io_dump.find_record(recs, step=step, substep=sub, probe_gid=g, field=field)
        col = a[g - 1] if a.ndim > 1 else np.atleast_1d(a[g - 1])
        worst = max(worst, compare_column(col, r, kind=kind).max_abs)
    return worst


def test_step1_surface_forcing(run3):
    """The bulk + SSS/runoff + shortwave-penetration surface fields match the C dump."""
    sfx, _ = run3["steps"][0]
    recs = run3["recs"]
    # node scalars (heat_flux through the M-O loop; the salt balance is a reduction)
    for fld, arr, tol in [("heat_flux", sfx.heat_flux, 1e-10),
                          ("water_flux", sfx.water_flux, 1e-14),
                          ("virtual_salt", sfx.virtual_salt, 1e-14),
                          ("relax_salt", sfx.relax_salt, 1e-14)]:
        worst = 0.0
        a = np.asarray(arr)
        for g in PROBES:
            r = io_dump.find_record(recs, step=1, substep=0, probe_gid=g, field=fld)
            worst = max(worst, abs(float(a[g - 1]) - float(r.values[0])))
        assert worst < tol, f"{fld}: max|Δ|={worst:.3e}"
    # the per-column shortwave temperature flux (MAP class)
    assert _maxabs(sfx.sw_3d, recs, 1, 0, "sw_3d", "map") < 1e-14


def test_step1_integrated_tracers_bitexact(run3):
    """Post-step-1 T/S match the C dump to bit-exact class — the comprehensive gate on
    the whole assembled CORE2 step (every kernel + the new surface BCs)."""
    _, st1 = run3["steps"][0]
    recs = run3["recs"]
    assert _maxabs(st1.T, recs, 1, 15, "T", "scatter") < 1e-11
    assert _maxabs(st1.S, recs, 1, 15, "S", "scatter") < 1e-11


def test_step1_dynamics_sanity(run3):
    """The pi dynamics kernels on CORE2 reproduce the dump: EOS density + N² are
    bit-exact-class (a non-rest gate — PHC stratification, unlike the rest-state test)."""
    _, st1 = run3["steps"][0]
    recs = run3["recs"]
    assert _maxabs(st1.density, recs, 1, 1, "density", "scatter") < 1e-10
    assert _maxabs(st1.bvfreq, recs, 1, 1, "bvfreq", "scatter") < 1e-11
    assert _maxabs(st1.Kv, recs, 1, 4, "Kv", "scatter") < 1e-12


def test_tracers_evolution_steps23(run3):
    """T/S stay scatter-class over steps 2–3 — the loop-carried forcing (jra date, AB2,
    the step≥2 ice-ocean drag) threads correctly."""
    recs = run3["recs"]
    for n in (2, 3):
        _, st = run3["steps"][n - 1]
        assert _maxabs(st.T, recs, n, 15, "T", "scatter") < 1e-6, f"T step {n}"
        assert _maxabs(st.S, recs, n, 15, "S", "scatter") < 1e-6, f"S step {n}"


def test_physical_and_finite(run3):
    """No NaNs; T/S stay in physical range over the short run (a smoke check)."""
    mesh = run3["mesh"]
    ml = np.asarray(mesh.node_layer_mask)
    for _, st in run3["steps"]:
        T = np.asarray(st.T)[ml]
        S = np.asarray(st.S)[ml]
        assert np.isfinite(T).all() and np.isfinite(S).all()
        assert T.min() > -3.0 and T.max() < 40.0
        assert S.min() > 0.0 and S.max() < 45.0
