"""Task G.7 (GATE 6B, the assembled gate): the full GM/Redi-ON CORE2 step matches
the C GM-ON per-substep dump.

Runs the assembled ocean step on CORE2 with ``gm_cfg=GMConfig()`` (the mesoscale eddy
parameterization wired in: the GM bolus advection + the Redi neutral-diffusion terms +
the K33 isoneutral augmentation) and the full Phase-5 surface forcing (PHC IC + JRA55
bulk + SSS/runoff + shortwave penetration, static-ice mask), and verifies the post-step
T/S against the C dump ``data/gm_step_dump_core2/core2_cdump.00000`` — generated by
``port2/jobs/jax_gm_dump_core2.sh`` at the **matched** config (PP, GM/Redi ON, ice
dyn/adv/thermo OFF, ``FESOM_BULK_FIXED_ITERS=1``, dt=500).

Where the per-kernel G.1–G.6 gates were bit-exact in isolation, this is the assembled
gate: the post-step T/S depend on every upstream kernel AND the whole GM/Redi chain (the
bolus-augmented advection + the two Redi explicit terms + K33). GM/Redi is deterministic
(no EVP-like reassociation floor, unlike the ice assembly), so the assembled step stays
TIGHT (~1e-9 .. 1e-12 scatter class), not climate-close.

Step-1 dynamics (density/bvfreq/Kv/d_eta/...) are GM-INDEPENDENT (the bolus is subtracted
back and Redi touches only the tracers, so GM never feeds the within-step momentum/SSH),
so they reproduce the same C dynamics as the no-GM step_dump — a useful cross-check that
the GM dump's dynamics state is the matched one.

SKIPS cleanly if the CORE2 mesh / PHC IC cache / GM step dump are absent.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from fesom_jax import surface_forcing, io_dump, ssh
from fesom_jax import step as stepmod
from fesom_jax.gm import GMConfig
from fesom_jax.mesh import load_mesh
from fesom_jax.phc_ic import core2_initial_state
from fesom_jax.verify import compare_column

ROOT = Path(__file__).resolve().parents[2]
MESH_DIR = ROOT / "data" / "mesh_core2"
IC_DIR = ROOT / "data" / "ic_core2"
DUMP = ROOT / "data" / "gm_step_dump_core2" / "core2_cdump.00000"
DT = 500.0
YEAR = 1958
NSTEPS = 2
# Node probes (the C dump's FESOM_DUMP_PROBES) — node fields (T, S, density, Kv, ...).
PROBES = [1001, 33778, 43828, 61202, 66921, 79663, 94122]

pytestmark = pytest.mark.skipif(
    not (MESH_DIR.exists() and (IC_DIR / "T_ic.npy").exists() and DUMP.exists()),
    reason="CORE2 mesh / PHC IC / GM step dump missing (run Task 5.1/5.2 + "
           "port2/jobs/jax_gm_dump_core2.sh)",
)


@pytest.fixture(scope="module")
def run_gm():
    """Build the CORE2 model + forcing and run ``NSTEPS`` eager GM-ON steps (eager
    ~32 s/step on CPU — run once for the module)."""
    mesh = load_mesh(MESH_DIR)
    state = core2_initial_state(mesh, IC_DIR)
    op = ssh.build_ssh_operator(mesh, dt=DT)
    cf = surface_forcing.build_surface_forcing(mesh, YEAR, sst_ic=np.asarray(state.T[:, 0]))
    fs = cf.static
    dates = surface_forcing.dates_for_steps(YEAR, DT, NSTEPS)
    recs = io_dump.load_records(DUMP)
    gm_cfg = GMConfig()

    states = []                              # state_after_n for n=1..NSTEPS
    st = state
    for n in range(NSTEPS):
        sf = cf.step_forcing(*dates[n])
        st = stepmod.step(st, mesh, op, None, dt=DT, is_first_step=(n == 0),
                          step_forcing=sf, forcing_static=fs, gm_cfg=gm_cfg)
        states.append(st)
    return dict(mesh=mesh, recs=recs, states=states)


def _maxabs(jax_arr, recs, step, sub, field, kind):
    """Max |Δ| over the NODE probe columns for one (step, substep, field)."""
    a = np.asarray(jax_arr)
    worst = 0.0
    for g in PROBES:
        r = io_dump.find_record(recs, step=step, substep=sub, probe_gid=g, field=field)
        col = a[g - 1] if a.ndim > 1 else np.atleast_1d(a[g - 1])
        worst = max(worst, compare_column(col, r, kind=kind).max_abs)
    return worst


def test_step1_gm_tracers(run_gm):
    """Post-step-1 T/S match the GM-ON C dump — the comprehensive assembled gate on the
    whole GM/Redi chain (bolus advection + G7a + G7b + K33) on top of every ocean kernel.
    Deterministic GM ⇒ TIGHT (scatter class)."""
    st1 = run_gm["states"][0]
    recs = run_gm["recs"]
    dT = _maxabs(st1.T, recs, 1, 15, "T", "scatter")
    dS = _maxabs(st1.S, recs, 1, 15, "S", "scatter")
    print(f"\nGM step-1 post-step: T max|Δ|={dT:.3e}  S max|Δ|={dS:.3e}")
    # Deterministic GM ⇒ bit-exact class (measured ~7e-15/2e-14, like the no-GM step_dump
    # gate's <1e-11) — NOT the ice assembly's climate-close ~1e-6.
    assert dT < 1e-11
    assert dS < 1e-11


def test_step1_dynamics_gm_independent(run_gm):
    """Step-1 dynamics reproduce the GM dump's dynamics (bit-exact class). GM does not
    feed the within-step momentum/SSH (the bolus is subtracted back; Redi touches only
    the tracers), so these are the same fields the no-GM step_dump carried — confirming
    the GM dump's dynamics state is the matched one."""
    st1 = run_gm["states"][0]
    recs = run_gm["recs"]
    assert _maxabs(st1.density, recs, 1, 1, "density", "scatter") < 1e-10
    assert _maxabs(st1.bvfreq, recs, 1, 1, "bvfreq", "scatter") < 1e-11
    assert _maxabs(st1.Kv, recs, 1, 4, "Kv", "scatter") < 1e-12
    assert _maxabs(st1.d_eta, recs, 1, 9, "d_eta", "scatter") < 1e-11
    assert _maxabs(st1.w, recs, 1, 13, "w", "scatter") < 1e-11


def test_evolution_step2_gm(run_gm):
    """Post-step-2 T/S stay scatter-class over the GM-ON evolution — the loop-carried
    forcing + AB2 history + the per-step recomputed GM/Redi thread correctly. Step 2
    inherits step 1's ~1e-12 spread (amplified by the CG iteration count); bounded, not
    growing catastrophically (the threading-correctness gate, not a tight match)."""
    if NSTEPS < 2:
        pytest.skip("NSTEPS<2")
    st2 = run_gm["states"][1]
    recs = run_gm["recs"]
    dT = _maxabs(st2.T, recs, 2, 15, "T", "scatter")
    dS = _maxabs(st2.S, recs, 2, 15, "S", "scatter")
    print(f"\nGM step-2 post-step: T max|Δ|={dT:.3e}  S max|Δ|={dS:.3e}")
    assert dT < 1e-6
    assert dS < 1e-6


def test_physical_and_finite(run_gm):
    """No NaNs; T/S stay in physical range over the short GM-ON run (a smoke check)."""
    mesh = run_gm["mesh"]
    ml = np.asarray(mesh.node_layer_mask)
    for st in run_gm["states"]:
        T = np.asarray(st.T)[ml]
        S = np.asarray(st.S)[ml]
        assert np.isfinite(T).all() and np.isfinite(S).all()
        assert T.min() > -3.0 and T.max() < 40.0
        assert S.min() > 0.0 and S.max() < 45.0
