"""CORE2 assembled step + surface forcing gate — Phase 5, Task 5.6 acceptance.

Runs the full assembled ocean step on the CORE2 mesh (PHC IC + JRA55 bulk + SSS/runoff
+ shortwave penetration + the static ice mask) and verifies it against the C per-substep
dump (``data/step_dump_core2/core2_cdump.00000``, generated by
``port2/jobs/jax_step_dump_core2.sh`` at the matched config: PP, no GM/Redi, ice
dyn/adv/thermo off, ``FESOM_BULK_FIXED_ITERS=1``, dt=500).

Three gates:

* **Surface forcing** (``compute_surface_fluxes`` from the PHC IC): ``heat_flux``
  (post-shortwave-penetration), ``water_flux``, ``virtual_salt``, ``relax_salt``,
  ``sw_3d`` — MAP/reduction class (~1e-13 .. 1e-20).
* **Integrated step 1** (one eager step): post-step ``T``/``S`` — **bit-exact-class**
  (~1e-14). This is the comprehensive gate: it depends on every upstream kernel (EOS,
  PGF, PP, momentum, CG SSH, ALE, FCT, vertical diffusion) AND the new surface BCs, so a
  tight match validates the whole assembled CORE2 step.
* **Evolution** (steps 2–3): post-step ``T``/``S`` stay scatter-class (~1e-9), validating
  the loop-carried forcing (jra date progression, AB2 history, the step≥2 ice-ocean drag).

SKIPS cleanly if the CORE2 mesh / PHC IC cache / dump fixture are absent.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from fesom_jax import core2_forcing, io_dump, ssh
from fesom_jax import step as stepmod
from fesom_jax.mesh import load_mesh
from fesom_jax.phc_ic import core2_initial_state
from fesom_jax.verify import compare_column

ROOT = Path(__file__).resolve().parents[2]
MESH_DIR = ROOT / "data" / "mesh_core2"
IC_DIR = ROOT / "data" / "ic_core2"
DUMP = ROOT / "data" / "step_dump_core2" / "core2_cdump.00000"
DT = 500.0
YEAR = 1958
NSTEPS = 3
# Node probes (the C dump's FESOM_DUMP_PROBES) — node fields (T, S, density, Kv,
# pressure, d_eta, eta_n, hbar, ssh_rhs, w, hnode...) are recorded here.
PROBES = [1001, 33778, 43828, 61202, 66921, 79663, 94122]
# The incident-element gids the C dump pairs with each node probe — ELEMENT fields
# (pgf_x/y, Av, uv_rhs_u/v, uv_u/v) are recorded here (fesom_dump.c s_elem_gid).
ELEM_PROBES = [307, 747, 25954, 61526, 99096, 110065, 154575]

pytestmark = pytest.mark.skipif(
    not (MESH_DIR.exists() and (IC_DIR / "T_ic.npy").exists() and DUMP.exists()),
    reason="CORE2 mesh / PHC IC / step dump missing (run Task 5.1/5.2 + "
           "port2/jobs/jax_step_dump_core2.sh)",
)


@pytest.fixture(scope="module")
def run3():
    """Build the CORE2 model + forcing and run ``NSTEPS`` eager steps, caching each
    step's surface fluxes + post-step state (eager ~32 s/step — run once for the
    module)."""
    mesh = load_mesh(MESH_DIR)
    state = core2_initial_state(mesh, IC_DIR)
    op = ssh.build_ssh_operator(mesh, dt=DT)
    cf = core2_forcing.build_core_forcing(mesh, YEAR, sst_ic=np.asarray(state.T[:, 0]))
    fs = cf.static
    dates = core2_forcing.dates_for_steps(YEAR, DT, NSTEPS)
    recs = io_dump.load_records(DUMP)

    steps = []                              # (sfx_n, state_after_n) for n=1..NSTEPS
    st = state
    for n in range(NSTEPS):
        sf = cf.step_forcing(*dates[n])
        sfx = core2_forcing.compute_surface_fluxes(mesh, st, sf, fs, dt=DT)
        st = stepmod.step(st, mesh, op, None, dt=DT, is_first_step=(n == 0),
                          step_forcing=sf, forcing_static=fs)
        steps.append((sfx, st))
    return dict(mesh=mesh, fs=fs, recs=recs, steps=steps)


def _maxabs(jax_arr, recs, step, sub, field, kind):
    """Max |Δ| over the NODE probe columns for one (step, substep, field)."""
    a = np.asarray(jax_arr)
    worst = 0.0
    for g in PROBES:
        r = io_dump.find_record(recs, step=step, substep=sub, probe_gid=g, field=field)
        col = a[g - 1] if a.ndim > 1 else np.atleast_1d(a[g - 1])
        worst = max(worst, compare_column(col, r, kind=kind).max_abs)
    return worst


def _emaxabs(jax_arr, recs, step, sub, field, comp, kind="scatter"):
    """Max |Δ| over the ELEMENT probe columns for an element field. ``comp`` picks
    the component column from the ``(elem2D, nl, 2)`` array (0=u, 1=v); pass
    ``None`` for a 2-D ``(elem2D, nl)`` field (pgf, Av)."""
    a = np.asarray(jax_arr)
    worst = 0.0
    for g in ELEM_PROBES:
        r = io_dump.find_record(recs, step=step, substep=sub, probe_gid=g, field=field)
        col = a[g - 1] if comp is None else a[g - 1, :, comp]
        worst = max(worst, compare_column(col, r, kind=kind).max_abs)
    return worst


def test_step1_surface_forcing(run3):
    """The bulk + SSS/runoff + shortwave-penetration surface fields match the C dump."""
    sfx, _ = run3["steps"][0]
    recs = run3["recs"]
    # node scalars (heat_flux through the M-O loop; the salt balance is a reduction)
    for fld, arr, tol in [("heat_flux", sfx.heat_flux, 1e-10),
                          ("water_flux", sfx.water_flux, 1e-14),
                          ("virtual_salt", sfx.virtual_salt, 1e-14),
                          ("relax_salt", sfx.relax_salt, 1e-14)]:
        worst = 0.0
        a = np.asarray(arr)
        for g in PROBES:
            r = io_dump.find_record(recs, step=1, substep=0, probe_gid=g, field=fld)
            worst = max(worst, abs(float(a[g - 1]) - float(r.values[0])))
        assert worst < tol, f"{fld}: max|Δ|={worst:.3e}"
    # the per-column shortwave temperature flux (MAP class)
    assert _maxabs(sfx.sw_3d, recs, 1, 0, "sw_3d", "map") < 1e-14


def test_step1_integrated_tracers_bitexact(run3):
    """Post-step-1 T/S match the C dump to bit-exact class — the comprehensive gate on
    the whole assembled CORE2 step (every kernel + the new surface BCs)."""
    _, st1 = run3["steps"][0]
    recs = run3["recs"]
    assert _maxabs(st1.T, recs, 1, 15, "T", "scatter") < 1e-11
    assert _maxabs(st1.S, recs, 1, 15, "S", "scatter") < 1e-11


def test_step1_dynamics_sanity(run3):
    """The pi dynamics kernels on CORE2 reproduce the dump: EOS density + N² are
    bit-exact-class (a non-rest gate — PHC stratification, unlike the rest-state test)."""
    _, st1 = run3["steps"][0]
    recs = run3["recs"]
    assert _maxabs(st1.density, recs, 1, 1, "density", "scatter") < 1e-10
    assert _maxabs(st1.bvfreq, recs, 1, 1, "bvfreq", "scatter") < 1e-11
    assert _maxabs(st1.Kv, recs, 1, 4, "Kv", "scatter") < 1e-12


def test_step1_dynamics_per_substep(run3):
    """Per-substep DYNAMICS on CORE2 reproduce the C dump at step 1 — bit-exact
    class. JAX and C start from the identical PHC IC, so every substep input
    matches and the only spread is FP reassociation. This makes explicit the
    chain the 5.6 T/S gate exercised only transitively:
    pressure → PGF → momentum-RHS/impl-visc → SSH-RHS → CG → update-vel → hbar →
    eta → ALE-w → thickness. Element fields (pgf/Av/uv_rhs/uv) at the incident-
    element probes, node fields at node probes.

    Tolerances are calibrated from the deterministic CPU run: pre-solve fields are
    ~0..1e-17, CG-derived fields ~1e-16..1e-14. ``pressure`` (~5e5 hydrostatic
    integral) and ``ssh_rhs`` (~1e5 transport-divergence ×area/dt) are large-
    magnitude, so their absolute floors scale up (~1e-11 *relative*)."""
    _, st1 = run3["steps"][0]
    recs = run3["recs"]
    # substep 1 — hydrostatic pressure (large integral) — node
    assert _maxabs(st1.hpressure, recs, 1, 1, "pressure", "scatter") < 1e-9
    # substep 3 — pressure-gradient force (pre-solve, deterministic) — element
    assert _emaxabs(st1.pgf_x, recs, 1, 3, "pgf_x", None) < 1e-12
    assert _emaxabs(st1.pgf_y, recs, 1, 3, "pgf_y", None) < 1e-12
    # substep 4 — element vertical viscosity Av (node Kv is in dynamics_sanity)
    assert _emaxabs(st1.Av, recs, 1, 4, "Av", None) < 1e-12
    # substep 7 — impl_vert_visc increment du (== st.uv_rhs) — element
    assert _emaxabs(st1.uv_rhs, recs, 1, 7, "uv_rhs_u", 0) < 1e-12
    assert _emaxabs(st1.uv_rhs, recs, 1, 7, "uv_rhs_v", 1) < 1e-12
    # substep 8 — SSH RHS (large transport-divergence field) — node
    assert _maxabs(st1.ssh_rhs, recs, 1, 8, "ssh_rhs", "scatter") < 5e-6
    # substep 9 — CG SSH solution d_eta (warm-start 0 at step 1) — node
    assert _maxabs(st1.d_eta, recs, 1, 9, "d_eta", "scatter") < 1e-11
    # substep 10 — velocity after the barotropic SSH-gradient correction — element
    assert _emaxabs(st1.uv, recs, 1, 10, "uv_u", 0) < 1e-11
    assert _emaxabs(st1.uv, recs, 1, 10, "uv_v", 1) < 1e-11
    # substeps 11/12 — hbar, eta_n — node
    assert _maxabs(st1.hbar, recs, 1, 11, "hbar", "scatter") < 1e-11
    assert _maxabs(st1.eta_n, recs, 1, 12, "eta_n", "scatter") < 1e-11
    # substep 13 — ALE vertical velocity w + static linfs hnode_new; substep 16 hnode
    assert _maxabs(st1.w, recs, 1, 13, "w", "scatter") < 1e-11
    assert _maxabs(st1.hnode_new, recs, 1, 13, "hnode_new", "map") < 1e-12
    assert _maxabs(st1.hnode, recs, 1, 16, "hnode", "map") < 1e-12


def test_evolution_steps23(run3):
    """T/S **and** the dynamics (uv, d_eta) stay scatter-class over steps 2–3 —
    the loop-carried forcing (jra date, AB2 history, the warm-started CG, the
    step≥2 ice-ocean drag) threads correctly. Unlike step 1 (bit-exact, identical
    inputs), steps 2–3 inherit the prior step's ~1e-15 spread and the discrete CG
    iteration count amplifies it to ~1e-9..1e-6 — bounded, not growing
    catastrophically (the threading-correctness gate, not a tight match)."""
    recs = run3["recs"]
    for n in (2, 3):
        _, st = run3["steps"][n - 1]
        assert _maxabs(st.T, recs, n, 15, "T", "scatter") < 1e-6, f"T step {n}"
        assert _maxabs(st.S, recs, n, 15, "S", "scatter") < 1e-6, f"S step {n}"
        assert _emaxabs(st.uv, recs, n, 10, "uv_u", 0) < 1e-4, f"uv_u step {n}"
        assert _emaxabs(st.uv, recs, n, 10, "uv_v", 1) < 1e-4, f"uv_v step {n}"
        assert _maxabs(st.d_eta, recs, n, 9, "d_eta", "scatter") < 1e-5, f"d_eta step {n}"


def test_physical_and_finite(run3):
    """No NaNs; T/S stay in physical range over the short run (a smoke check)."""
    mesh = run3["mesh"]
    ml = np.asarray(mesh.node_layer_mask)
    for _, st in run3["steps"]:
        T = np.asarray(st.T)[ml]
        S = np.asarray(st.S)[ml]
        assert np.isfinite(T).all() and np.isfinite(S).all()
        assert T.min() > -3.0 and T.max() < 40.0
        assert S.min() > 0.0 and S.max() < 45.0
